### ISSUE TITLE
error: list index out of range

### ISSUE THREAD

**Issue by skriptk** [xtekky/TikTok-ViewBot#101]
after inserting video link it returns the 'list index out of range' then asks to restart

if it succeeds past entering the video link, it will say sleeping and then sending, but return the same error briefly after trying to send.

when i first tried using it, it said succeeded but yielded no views

**Comment by Pumkin786** [comment]
Same issue its not working

**Comment by PJMeyer1** [comment]
I have the same issue 

The first time I did it put the video link it returns said successful but no views.

Then trying it again the 'list index out of range' then asks to restart

But when I fill the captcha it says there is no command prompt

**Comment by hamzabilinwal** [comment]
same issue help please
