### ISSUE TITLE
Check access to Zefoy

### ISSUE THREAD

**Issue by bigboss97lnt** [xtekky/TikTok-ViewBot#105]
Hello there,

I'm running: both 'old/v1/to update/viewbot.py' and 'old/v1/viewbot.py', I've also updated 'old/v1/to update/config.json' and added the video ID as instructed.

After running both scripts I got the following:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/64983216/218253633-fa002d8c-31fc-4726-a41d-ccf097ca063a.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/64983216/218253648-0e64525f-75ce-4ee9-afdb-6424e021f1cf.png">

**Comment by bigboss97lnt** [comment]
I guess the issue is here? 'TikTok-ViewBot/old/v1/to update/viewbot.py'

<img width="560" alt="image" src="https://user-images.githubusercontent.com/64983216/218254522-82673c7f-6a46-4f37-bc98-958ee72a3db6.png">

**Comment by xtekky** [comment]
Hi, I am going to update the script soon enough
