### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by AntoineKM** [xtekky/TikTok-ViewBot#11]
I'll take screen shots tomorrow

**Comment by xtekky** [comment]
yes, please give me some examples and errors you encounter or I won't be able to do anything

**Comment by damiankrzyz** [comment]
It's working for me one closing bracket was missing

![Screenshot 2022-07-12 at 21 20 03](https://user-images.githubusercontent.com/79311645/178587544-c057f50d-9e25-4dce-b08e-6da67d1e08be.png)
![Screenshot 2022-07-12 at 21 19 04](https://user-images.githubusercontent.com/79311645/178587547-042517c1-a02e-496d-8411-b71be9aaeca3.png)

Thank you for the bot @xtekky

**Comment by AntoineKM** [comment]
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/54948363/178728153-df8c96c0-3fdf-4d3c-a94f-3a32a3c53e38.png">

**Comment by xtekky** [comment]
I know what the problem is, let me fix it

**Comment by AntoineKM** [comment]
everything is working fine now tks !
