### ISSUE TITLE
Android Setup Process?

### ISSUE THREAD

**Issue by scriptxd** [xtekky/TikTok-ViewBot#113]
Termux/Ubuntu 64 bit

**Comment by 9fo** [comment]
What do u mean? It's a simple program created with Python. U can just do sudo install python3 to run it

**Comment by akhtarmuzamil42-ops** [comment]
https://www.tiktok.com/@muzamilakhtar74/video/7536949799854165255?_r=1&u_code=e8kmfmlc47kg1l&preview_pb=0&sharer_language=en&_d=e16h0i5ld7lh3i&share_item_id=7536949799854165255&source=h5_m&timestamp=1754836453&user_id=7251822454409004037&sec_user_id=MS4wLjABAAAAupYkhbDTxfdsQ8hhk6o8PXJt2SYLaHSFzITsEP0_D10o4Ic-u-3dHPP2DYN4WpYX&item_author_type=1&social_share_type=0&utm_source=copy&utm_campaign=client_share&utm_medium=android&share_iid=7533107239796754183&share_link_id=9310b159-0722-4a22-8bb2-e01a13305cc7&share_app_id=1233&ugbiz_name=MAIN&ug_btm=b8727%2Cb2878&link_reflow_popup_iteration_sharer=%7B%22click_empty_to_play%22%3A1%2C%22dynamic_cover%22%3A1%2C%22follow_to_play_duration%22%3A-1.0%2C%22profile_clickable%22%3A1%7D&enable_checksum=1
