### ISSUE TITLE
Zefoy Error 👎🏻 

### ISSUE THREAD

**Issue by SIAMRAHMAN000** [xtekky/TikTok-ViewBot#117]
![image](https://user-images.githubusercontent.com/118335510/223026062-7c50a9c4-825e-48c8-89ad-8c198167e0d0.png)
![image](https://user-images.githubusercontent.com/118335510/223026238-95cc0e37-257f-4b71-92d1-67030b814a6e.png)

FIX THIS ISSU

**Comment by RealHeha** [comment]
did you fix this
