### ISSUE TITLE
Please login

### ISSUE THREAD

**Issue by NonJokeMan** [xtekky/TikTok-ViewBot#120]
Failed to search link [list index out of range]
<div style="font-size:110%;font-weight:bold;color:#333;">Session expired. Please re-login. <span><a href="/" style="text-decoration:none">CLICK HERE</a></span></div>

**Comment by 9fo** [comment]
Re log in.

**Comment by BearrXW** [comment]
> Re log in.

we know that mate it still doesn't work.
