### ISSUE TITLE
Mobile issue

### ISSUE THREAD

**Issue by scriptxd** [xtekky/TikTok-ViewBot#15]
Wow...
Working On Android But Need Little Bit Optimization....

Can U Bypass Countdown...

**Comment by xtekky** [comment]
I will make an android only version, and no u can't bypass timer

**Comment by scriptxd** [comment]
> I will make an android only version, and no u can't bypass timer

Okk...


User Agent:
Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.129 Mobile Safari/537.36

**Comment by xtekky** [comment]
Not in public, will add at 250 stars

**Comment by xtekky** [comment]
and check out https://github.com/xtekky/TikTok-ViewBot/blob/main/mobile/mobile_script.py
made script for mobile

**Comment by scriptxd** [comment]
> Not in public, will add at 250 stars

❤️❤️❤️

**Comment by scriptxd** [comment]
> and check out https://github.com/xtekky/TikTok-ViewBot/blob/main/mobile/mobile_script.py made script for mobile

Thanks❤️

**Comment by xtekky** [comment]
its for better performance but I'll add it again ; )

**Comment by scriptxd** [comment]
> its for better performance but I'll add it again ; )

Should Improve  Connection & Auto Season Generate After Season Expire.....

Auto Refresh If Failed To Solve Captcha.....


❤️

**Comment by Mrdexr** [comment]
> 

Agree.....❤️
