### ISSUE TITLE
error line 27

### ISSUE THREAD

**Issue by mokhtarakel** [xtekky/TikTok-ViewBot#40]
File "viewbot.py", line 27
    return f"""                      {Col.Symbol(symbol, self.lblue, self.blue)} {self.lblue}{text}{Col.reset}"""
                                                                                                                ^
SyntaxError: invalid syntax

**Comment by scriptxd** [comment]
First install all requirements....

**Comment by mokhtarakel** [comment]
every think is installed, but still the same error

**Comment by mokhtarakel** [comment]
I am working in ubuntu server

**Comment by mokhtarakel** [comment]
still give me the same error, any help??
