### ISSUE TITLE
Fix Sir

### ISSUE THREAD

**Issue by scriptxd** [xtekky/TikTok-ViewBot#41]
![Screenshot_2022_0923_170747](https://user-images.githubusercontent.com/104721718/191954063-8e1c57ad-d97a-4515-bf2d-972e5054a313.jpg)

Fix This For Viewbot.py

Fix 👉 line 32
    json_data =  {
                  ^
IndentationError: unindent does not match any outer indentation level👈   For mobile_script.py
(Maybe Space Related Issue) Not Sure

**Comment by IntrinsicInnovation** [comment]
doesn't work.    anything that actually works?
