### ISSUE TITLE
Fixing bot

### ISSUE THREAD

**Issue by xtekky** [xtekky/TikTok-ViewBot#43]

**Comment by xtekky** [comment]
temp fix uploaded with new devices, currently working well

**Comment by andhiko** [comment]
![Screenshot_20221019-203205_Termux](https://user-images.githubusercontent.com/41241665/196705722-d81fd7d3-cddc-4eb2-bc7d-92f715edb922.jpg)

**Comment by xtekky** [comment]
patched, working on an update

**Comment by xtekky** [comment]
fixed
