### ISSUE TITLE
Devices Dead 

### ISSUE THREAD

**Issue by 0xNyaku** [xtekky/TikTok-ViewBot#59]
RIP devices x)

**Comment by xtekky** [comment]
I don't think the devices, Tikok patched something again, idk if I publish an unpatched version or just zefoy

**Comment by 0xNyaku** [comment]
Auto-Zefoy programs are already public in GitHub so i dont think it will be useful

**Comment by Bulbullshit** [comment]
not work now :(

**Comment by xtekky** [comment]
yh they are all outdated
