### ISSUE TITLE
Views video length

### ISSUE THREAD

**Issue by xanderusa** [xtekky/TikTok-ViewBot#64]
Can you please confirm if the views sent are actually watching the entire length of the video or it's just touching the ip address or how it works? I ask this tiktok likes retention.  Thank you for your answer.

**Comment by DuBarTech** [comment]
> Can you please confirm if the views sent are actually watching the entire length of the video or it's just touching the ip address or how it works? I ask this tiktok likes retention. Thank you for your answer.

please to everyone **I have found better bot** check: https://dbtechlabs.com 
**I AM NOT AFFILIATED** with them only I have looking for the same issue and I have found this site so thank me later

**Comment by xtekky** [comment]
its not
