### ISSUE TITLE
Read This Before Making An Issue.

### ISSUE THREAD

**Issue by nightclubs** [xtekky/TikTok-ViewBot#70]
The error you're most likely seeing is 
```py
{'captcha_answer': None, 'status_code': 1}
``` 
I understand this, please be patient and wait for Tekky to fix his image recognition.

**Comment by xtekky** [comment]
love ya

**Comment by Thakshara9728** [comment]
yeah same

> The error you're most likely seeing is
> 
> ```python
> {'captcha_answer': None, 'status_code': 1}
> ```
> 
> I understand this, please be patient and wait for Tekky to fix his image recognition.

**Comment by xtekky** [comment]
solved

**Comment by Thakshara9728** [comment]
> solved

Thanx but still same https://prnt.sc/wVk1L8W-u9-w

**Comment by Mafiosoweb1** [comment]
Hello, it does work for me, just asking how do i change the mode.

**Comment by TeddyInWeb** [comment]
![image](https://user-images.githubusercontent.com/32919681/202122785-c3c7cc59-77ea-4a0d-b440-46a82992be7c.png)
need help..

**Comment by Bulbullshit** [comment]
please make a bot for azubis.live sir, thanks

**Comment by ronmegini** [comment]
Same issue for me - Windows version 10, python version 3.11.
<img width="766" alt="image" src="https://user-images.githubusercontent.com/58236438/202796139-60ec320c-7e94-4cb6-bae5-4b7598dd1caa.png">
The system needs any requirements such as a python or module version to work?
