### ISSUE TITLE
Doesnt work on VMInstance

### ISSUE THREAD

**Issue by paulwababu** [xtekky/TikTok-ViewBot#77]
wanted to deploy on VMinstance but isnt working. On locahost its working fine
is the access blocked internationally?

**Comment by xtekky** [comment]
Please elaborate

**Comment by paulwababu** [comment]
When I run the code on a VMInstance, I get a captcha answer None error code and the code asks me to restart. But when I run it on my local host. It's working fine. 
Here is am image of the error on the server.
![Screenshot_20221122-112554_Google Cloud](https://user-images.githubusercontent.com/44939805/203263409-37e8a216-65c4-445c-a5ca-088585bf65db.jpg)

**Comment by paulwababu** [comment]
😂 😂
