### ISSUE TITLE
pystyle error

### ISSUE THREAD

**Issue by Alexloi4071** [xtekky/TikTok-ViewBot#80]
![image](https://user-images.githubusercontent.com/118339744/203830144-40170171-274a-4840-bcdd-5b1e69daab24.png)
![image](https://user-images.githubusercontent.com/118339744/203830253-87a0e29c-6e2c-4602-b2cf-da5fa1b40768.png)

when i run the bot .show pystyle have some problem. But i have already install pystyle in python

**Comment by xtekky** [comment]
reinstall it then, this has nothing to do with my script but rather the package itself
